# Copyright 1998-2019 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

set(HYPRE_COMPILER "HYPRE_COMPILER_CLANG" CACHE STRING "")

set(CMAKE_CXX_COMPILER "/soft/compilers/llvm/5.0/bin/clang++" CACHE PATH "")
set(CMAKE_C_COMPILER "/soft/compilers/llvm/5.0/bin/clang" CACHE PATH "")

set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} -O3" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O0 -g" CACHE STRING "")

set(HYPRE_RANGE_ALIGN 4 CACHE INT "")
set(HYPRE_RANGE_MIN_LENGTH 32 CACHE INT "")
set(HYPRE_DATA_ALIGN 64 CACHE INT "")

set(HYPRE_HOST_CONFIG_LOADED On CACHE Bool "")
